//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.VisualBasic.ApplicationServices;

namespace My
{
    //NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    // or if you encounter build errors in this file, go to the Project Designer
    // (go to Project Properties or double-click the My Project node in
    // Solution Explorer), and make changes on the Application tab.
    //
    internal partial class MyApplication : WindowsFormsApplicationBase
    {
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public MyApplication() :
            base(AuthenticationMode.Windows)
        {
            this.IsSingleInstance = false;
            this.EnableVisualStyles = true;
            this.SaveMySettingsOnExit = true;
            this.ShutdownStyle = Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses;
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        protected override void OnCreateMainForm()
        {
            this.MainForm = new Form1();
        }
    }
}
